/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apphibernatecolmenaralberto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM2A-03
 */
public class InterfazHibernateColmenarAlberto extends javax.swing.JFrame {

    AppHibernateColmenarAlberto AppHibernate;

    public InterfazHibernateColmenarAlberto() {
        initComponents();
        AppHibernate = new AppHibernateColmenarAlberto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void reiniciarInterfaz() {
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel5.setEnabled(false);
        jLabel6.setEnabled(false);
        jLabel7.setEnabled(false);
        jLabel8.setEnabled(false);
        jLabel9.setEnabled(false);
        comboVuelos.setEnabled(false);
        cajaCodigo.setEnabled(false);
        cajaCodigo.setEditable(true);
        cajaCodigo.setText("");
        cajaHoraSalida.setEnabled(false);
        cajaHoraSalida.setText("");
        cajaDestino.setEnabled(false);
        cajaDestino.setText("");
        cajaProcedencia.setEnabled(false);
        cajaProcedencia.setText("");
        cajaFumador.setEnabled(false);
        cajaFumador.setText("");
        cajaNoFumador.setEnabled(false);
        cajaNoFumador.setText("");
        cajaTurista.setEnabled(false);
        cajaTurista.setText("");
        cajaPrimera.setEnabled(false);
        cajaPrimera.setText("");
        botonSiguiente.setEnabled(false);
        botonSiguiente.setText("Siguiente");
        textoError.setText("");
    }
    
    public void rellenarComboVuelos() {
        if (comboVuelos.getItemCount() == 0) {
            List<Vuelos> lista = new ArrayList();
            lista = AppHibernate.obtenerListaVuelos();
            for (Vuelos vuelo : lista) {
                comboVuelos.addItem(vuelo.getCodVuelo());
            }
        }
    }
    
    public boolean camposRellenos() {
        return !cajaCodigo.getText().equals("") && !cajaHoraSalida.getText().equals("") && 
                !cajaDestino.getText().equals("") && !cajaProcedencia.getText().equals("") && 
                !cajaFumador.getText().equals("") && !cajaNoFumador.getText().equals("") && 
                !cajaTurista.getText().equals("") && !cajaPrimera.getText().equals("");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonInsertar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        comboVuelos = new javax.swing.JComboBox<>();
        cajaCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaHoraSalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaDestino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cajaProcedencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaFumador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaNoFumador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaTurista = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cajaPrimera = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonSiguiente = new javax.swing.JButton();
        textoError = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonInsertar.setText("Insertar Vuelo");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar Vuelo");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar Vuelo");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonConsultar.setText("Consultar Vuelos");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        comboVuelos.setEnabled(false);
        comboVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVuelosActionPerformed(evt);
            }
        });

        cajaCodigo.setEnabled(false);

        jLabel2.setText("Código");
        jLabel2.setEnabled(false);

        jLabel3.setText("Hora Salida");
        jLabel3.setEnabled(false);

        cajaHoraSalida.setEnabled(false);

        jLabel4.setText("Destino");
        jLabel4.setEnabled(false);

        cajaDestino.setEnabled(false);

        jLabel5.setText("Procedencia");
        jLabel5.setEnabled(false);

        cajaProcedencia.setEnabled(false);

        jLabel6.setText("Plazas Fumador");
        jLabel6.setEnabled(false);

        cajaFumador.setEnabled(false);

        jLabel7.setText("Plazas No Fumador");
        jLabel7.setEnabled(false);

        cajaNoFumador.setEnabled(false);

        jLabel8.setText("Plazas Turistas");
        jLabel8.setEnabled(false);

        cajaTurista.setEnabled(false);

        jLabel9.setText("Plazas Primera");
        jLabel9.setEnabled(false);

        cajaPrimera.setEnabled(false);

        jLabel1.setText("Escoge el vuelo");
        jLabel1.setEnabled(false);

        botonSiguiente.setText("Siguiente");
        botonSiguiente.setEnabled(false);
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "HoraSalida", "Destino", "Procedencia", "PlazasFumador", "PlazasNoFumador", "PlazasTuristas", "PlazasPrimera"
            }
        ));
        tablaVuelos.setEnabled(false);
        jScrollPane1.setViewportView(tablaVuelos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaFumador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaNoFumador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonSiguiente)
                                .addGap(18, 18, 18)
                                .addComponent(textoError)))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInsertar)
                    .addComponent(botonModificar)
                    .addComponent(botonBorrar)
                    .addComponent(botonConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cajaHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cajaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cajaProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cajaFumador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cajaNoFumador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cajaTurista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cajaPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiguiente)
                    .addComponent(textoError))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        reiniciarInterfaz();
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel6.setEnabled(true);
        jLabel7.setEnabled(true);
        jLabel8.setEnabled(true);
        jLabel9.setEnabled(true);
        cajaCodigo.setEnabled(true);
        cajaHoraSalida.setEnabled(true);
        cajaDestino.setEnabled(true);
        cajaProcedencia.setEnabled(true);
        cajaFumador.setEnabled(true);
        cajaNoFumador.setEnabled(true);
        cajaTurista.setEnabled(true);
        cajaPrimera.setEnabled(true);
        botonSiguiente.setEnabled(true);
        botonSiguiente.setText("Insertar");
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        String operacion = botonSiguiente.getText();
        if (operacion.equals("Insertar")) {
            textoError.setText("");
            if (!camposRellenos()) {
                textoError.setText("Introduce todos los campos");
            } else {
                AppHibernate.insertarVuelo(cajaCodigo.getText(), cajaHoraSalida.getText(), 
                        cajaDestino.getText(), cajaProcedencia.getText(), Integer.parseInt(cajaFumador.getText()), 
                        Integer.parseInt(cajaNoFumador.getText()), Integer.parseInt(cajaTurista.getText()), 
                        Integer.parseInt(cajaPrimera.getText()));
                comboVuelos.addItem(cajaCodigo.getText());
                reiniciarInterfaz();
                textoError.setText("Insertado correctamente");
            }
        } else if (operacion.equals("Modificar")) {
            if (!camposRellenos()) {
                textoError.setText("Introduce todos los campos");
            } else {
                AppHibernate.modificarVuelo(cajaCodigo.getText(), cajaHoraSalida.getText(), 
                    cajaDestino.getText(), cajaProcedencia.getText(), Integer.parseInt(cajaFumador.getText()), 
                    Integer.parseInt(cajaNoFumador.getText()), Integer.parseInt(cajaTurista.getText()), 
                    Integer.parseInt(cajaPrimera.getText()));
                reiniciarInterfaz();
                textoError.setText("Modificado correctamente");
            }
        } else if (operacion.equals("Borrar")) {
            String codigoVuelo = (String) comboVuelos.getSelectedItem();
            AppHibernate.borrarVuelo(codigoVuelo);
            comboVuelos.removeItem(codigoVuelo);
            reiniciarInterfaz();
            textoError.setText("Borrado correctamente");
        } else if (operacion.equals("Consultar")) {
            DefaultTableModel tabla = AppHibernate.consultarVuelos("", "");
            tablaVuelos.setModel(tabla);
        }
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        reiniciarInterfaz();
        jLabel1.setEnabled(true);
        comboVuelos.setEnabled(true);
        botonSiguiente.setEnabled(true);
        botonSiguiente.setText("Modificar");
        rellenarComboVuelos();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void comboVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVuelosActionPerformed
        String codVuelo = String.valueOf(comboVuelos.getSelectedItem());
        Vuelos vuelo = AppHibernate.obtenerVuelo(codVuelo);
        if (botonSiguiente.getText().equals("Modificar")) {
            jLabel2.setEnabled(true);
            jLabel3.setEnabled(true);
            jLabel4.setEnabled(true);
            jLabel5.setEnabled(true);
            jLabel6.setEnabled(true);
            jLabel7.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            cajaCodigo.setEnabled(true);
            cajaCodigo.setEditable(false);
            cajaHoraSalida.setEnabled(true);
            cajaDestino.setEnabled(true);
            cajaProcedencia.setEnabled(true);
            cajaFumador.setEnabled(true);
            cajaNoFumador.setEnabled(true);
            cajaTurista.setEnabled(true);
            cajaPrimera.setEnabled(true);
            botonSiguiente.setEnabled(true);
        }
        cajaCodigo.setText(vuelo.getCodVuelo());
        cajaHoraSalida.setText(vuelo.getHoraSalida());
        cajaDestino.setText(vuelo.getDestino());
        cajaProcedencia.setText(vuelo.getProcedencia());
        cajaFumador.setText(vuelo.getPlazasFumador().toString());
        cajaNoFumador.setText(vuelo.getPlazasNoFumador().toString());
        cajaTurista.setText(vuelo.getPlazasTurista().toString());
        cajaPrimera.setText(vuelo.getPlazasPrimera().toString());
    }//GEN-LAST:event_comboVuelosActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        reiniciarInterfaz();
        rellenarComboVuelos();
        jLabel1.setEnabled(true);
        comboVuelos.setEnabled(true);
        botonSiguiente.setEnabled(true);
        botonSiguiente.setText("Borrar");
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        reiniciarInterfaz();
        jLabel4.setEnabled(true);
        cajaDestino.setEnabled(true);
        jLabel5.setEnabled(true);
        cajaProcedencia.setEnabled(true);
        botonSiguiente.setEnabled(true);
        botonSiguiente.setText("Consultar");
    }//GEN-LAST:event_botonConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHibernateColmenarAlberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHibernateColmenarAlberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHibernateColmenarAlberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHibernateColmenarAlberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazHibernateColmenarAlberto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JTextField cajaDestino;
    private javax.swing.JTextField cajaFumador;
    private javax.swing.JTextField cajaHoraSalida;
    private javax.swing.JTextField cajaNoFumador;
    private javax.swing.JTextField cajaPrimera;
    private javax.swing.JTextField cajaProcedencia;
    private javax.swing.JTextField cajaTurista;
    private javax.swing.JComboBox<String> comboVuelos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVuelos;
    private javax.swing.JLabel textoError;
    // End of variables declaration//GEN-END:variables
}
