--------------------------------------------------------
-- Archivo creado  - viernes-febrero-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure VERVENTAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ANONYMOUS"."VERVENTAS" (ID NUMBER)
AS 
    CANTIDAD NUMBER;
    IMPORTE NUMBER;
    TOTALVENTA NUMBER;
    LIN NUMBER;
    PRODUCT TPRODUCTO := TPRODUCTO(NULL,NULL,NULL,NULL);
    CLIENT TCLIENTE := TCLIENTE(NULL,NULL,NULL,NULL,NULL);
    DIREC TDIRECCION := TDIRECCION(NULL,NULL,NULL,NULL);
    FECHA DATE;
    CURSOR C1 IS SELECT NUMLINEA, DEREF(IDPRODUCTO), CANTIDAD FROM THE (SELECT T.LINEAS FROM TABLAVENTAS T WHERE IDVENTA = ID);
BEGIN
    SELECT DEREF (IDCLIENTE), FECHAVENTA, V.CALCULATOTALVENTAS() INTO CLIENT, FECHA, TOTALVENTA
    FROM TABLAVENTAS V WHERE IDVENTA = ID;
    DIREC := CLIENT.DIREC;
    DBMS_OUTPUT.PUT_LINE('NUMERO DE VENTA: ' || ID || ' FECHA DE VENTA: ' || FECHA);
    DBMS_OUTPUT.PUT_LINE('NOMBRE DEL CLIENTE: ' || CLIENT.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('DIRECCION: ' || DIREC.CALLE);
    
    OPEN C1;
    FETCH C1 INTO LIN, PRODUCT, CANTIDAD;
    WHILE C1%FOUND LOOP
        IMPORTE := CANTIDAD * PRODUCT.PRECIO;
        DBMS_OUTPUT.PUT_LINE(LIN || '-' || PRODUCT.DESCRIPCION || ': ' || PRODUCT.PRECIO ||' * ' || CANTIDAD ||' = ' || IMPORTE);
        FETCH C1 INTO LIN, PRODUCT, CANTIDAD;
    END LOOP;
CLOSE C1;
DBMS_OUTPUT.PUT_LINE('TOTAL VENTA: ' || TOTALVENTA);
  
END VERVENTAS;

/
