--------------------------------------------------------
-- Archivo creado  - lunes-febrero-19-2024   
--------------------------------------------------------
REM INSERTING into ANONYMOUS.TABLAPRODUCTOS
SET DEFINE OFF;
Insert into ANONYMOUS.TABLAPRODUCTOS (IDPRODUCTO,DESCRIPCION,PRECIO,EXISTENCIAS) values ('1','Bicicleta city','100','5');
Insert into ANONYMOUS.TABLAPRODUCTOS (IDPRODUCTO,DESCRIPCION,PRECIO,EXISTENCIAS) values ('2','Monitor','50','10');
Insert into ANONYMOUS.TABLAPRODUCTOS (IDPRODUCTO,DESCRIPCION,PRECIO,EXISTENCIAS) values ('3','Ratón','30','40');
Insert into ANONYMOUS.TABLAPRODUCTOS (IDPRODUCTO,DESCRIPCION,PRECIO,EXISTENCIAS) values ('4','Mesa','50','25');
Insert into ANONYMOUS.TABLAPRODUCTOS (IDPRODUCTO,DESCRIPCION,PRECIO,EXISTENCIAS) values ('5','Silla','200','10');
Insert into ANONYMOUS.TABLAPRODUCTOS (IDPRODUCTO,DESCRIPCION,PRECIO,EXISTENCIAS) values ('6','Ventilador','30','20');
Insert into ANONYMOUS.TABLAPRODUCTOS (IDPRODUCTO,DESCRIPCION,PRECIO,EXISTENCIAS) values ('7','Cable','10','20');
