--------------------------------------------------------
-- Archivo creado  - viernes-febrero-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TABLACLIENTES
--------------------------------------------------------

  CREATE TABLE "ANONYMOUS"."TABLACLIENTES" OF "ANONYMOUS"."TCLIENTE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ANONYMOUS.TABLACLIENTES
SET DEFINE OFF;
Insert into ANONYMOUS.TABLACLIENTES (IDCLIENTE,NOMBRE,DIREC,NIF,TEL) values ('1','Luis García',ANONYMOUS.TDIRECCION('C/Dalias,22', 'Sevilla', 44330, 'Sevilla'),'34343434L',ANONYMOUS.TTELEFONO('950234577', '67899003'));
Insert into ANONYMOUS.TABLACLIENTES (IDCLIENTE,NOMBRE,DIREC,NIF,TEL) values ('2','Roberto García',ANONYMOUS.TDIRECCION('C/Falsa,123', 'Granada', 10330, 'Granada'),'5656565L',ANONYMOUS.TTELEFONO('58634577', '46329003'));
--------------------------------------------------------
--  DDL for Index SYS_C008732
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANONYMOUS"."SYS_C008732" ON "ANONYMOUS"."TABLACLIENTES" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008733
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANONYMOUS"."SYS_C008733" ON "ANONYMOUS"."TABLACLIENTES" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008734
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANONYMOUS"."SYS_C008734" ON "ANONYMOUS"."TABLACLIENTES" ("NIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TABLACLIENTES
--------------------------------------------------------

  ALTER TABLE "ANONYMOUS"."TABLACLIENTES" ADD PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANONYMOUS"."TABLACLIENTES" ADD UNIQUE ("SYS_NC_OID$") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANONYMOUS"."TABLACLIENTES" ADD UNIQUE ("NIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
